"""add sale_ends_at to products

Revision ID: e1769c1f01ea
Revises: 6289f6eb03b8
Create Date: 2026-05-02 23:40:16.725473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1769c1f01ea'
down_revision: Union[str, None] = '6289f6eb03b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sale_ends_at')
    # ### end Alembic commands ###
